name : Vérification du pokédex

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  structural-check:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Vérifier que le fichier existe
        run: test -f index.html